### ISSUE TITLE
confirm we can create draft issues through API.

### ISSUE THREAD

**Issue by Drew-Macgibbon** [incubrain/feedback-module#6]
These are what we will use in the `Ideas` column, we need to confirm that these can be created through the API.

See and example [here](https://github.com/orgs/incubrain/projects/2/views/1?pane=issue&itemId=40224196)

**Comment by JapneetRajput** [comment]
Yes this can be created through the API.

Here is the documentation for that

**Comment by Drew-Macgibbon** [comment]
@JapneetRajput the docs you linked to are for the REST API. We will be using the `graphql` one. I'm not sure it's as feature complete, so just need to make sure it can do the same.

**Comment by Drew-Macgibbon** [comment]
This is tested and working
