### ISSUE TITLE
what are the criteria / restrictions on GH Apps

### ISSUE THREAD

**Issue by Drew-Macgibbon** [incubrain/feedback-module#9]
We just need to clarify if this is a viable option for most of our users. This will increase the token limit by 3x.

**It should be easy and free**

**Comment by JapneetRajput** [comment]
I tried creating a GitHub app. They have given proper documentation for each option while creating one ([docs](https://docs.github.com/en/apps/creating-github-apps/registering-a-github-app/registering-a-github-app).

They've provided proper instructions for registering a GH App. It shouldn't take more than 15mins to make one. 

As far as I've checked the docs it is free.

**Comment by Drew-Macgibbon** [comment]
@JapneetRajput research if we can we increase GH APP graphql token limit if users exceed 15,000 limit.

**Comment by Drew-Macgibbon** [comment]
### Decision:
Because we have 5k token limit for PATs and that appears to service ~100k MAUs (even 10k would be fine), we will focus entirely on using PATs with the option to create multiple tokens and rotate if limits are exceeded. 

**In the future (1-2 years)  we will have an option to create a GH APP for users that need to scale**

### Research from [docs](https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/deciding-when-to-build-a-github-app)
- GitHub Apps have built-in, centralized webhooks. GitHub Apps can receive webhook events for all repositories and organizations the app can access. Conversely, OAuth apps must configure webhooks individually for each repository and organization.
- GitHub Apps provide more control over what the app can do. Instead of the broad scopes that OAuth apps use, GitHub Apps use fine-grained permissions.
- GitHub Apps can act independently of a user. This is beneficial for automations that do not require user input.
- GitHub Apps are not tied to a user account and do not consume a seat on GitHub. GitHub Apps remain installed even when the person who initially installed the app leaves the organization.
- The rate limit for GitHub Apps using an installation access token scales with the number of repositories and number of organization users.

### GH APP vs PAT:
- If you want to access GitHub resources on behalf of a user or in an organization, or you anticipate a long-lived integration, we recommend building a GitHub App.
- You can use personal access tokens for API testing or short-lived scripts. Since a personal access token is associated with a user, your automation could break if the user no longer has access to the resources you need. A GitHub App installed in an organization is not dependent on a user. Additionally, unlike a user, a GitHub App does not consume a GitHub seat.
